import './globals.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import Footer from '@/components/screens/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'МАР-КО',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={inter.className}>{children}</body>
      {/* <Footer /> */}
    </html>
  )
}
